export const NOTIFICAR = "NOTIFICAR";

export const ADICIONA_PROJETO = "ADICIONA_PROJETO";
export const ALTERA_PROJETO = "ALTERA_PROJETO";
export const EXCLUI_PROJETO = "EXCLUI_PROJETO";
export const DEFINI_PROJETO = "DEFINI_PROJETO";

export const DEFINI_TAREFAS = "DEFINI_TAREFAS";
export const ADICIONA_TAREFA = "ADICIONA_TAREFA";
export const ALTERA_TAREFA = "ALTERA_TAREFA";
