export const OBTER_PROJETOS = "OBTER_PROJETOS";
export const CADASTRA_PROJETO = "CADASTRA_PROJETO";
export const ALTERAR_PROJETO_ACTION = "ALTERAR_PROJETO";
export const EXCLUIR_PROJETO_ACTION = "EXCLUIR_PROJETO";

export const OBTER_TAREFAS = "OBTER_TAREFAS";
export const CADASTRAR_TAREFA = "CADASTRAR_TAREFA";
export const ALTERAR_TAREFA = "ALTERAR_TAREFA";
